### ISSUE TITLE
单币swap的时候，建议按钮变成：enable，或者未授权前不可点击状态。以及未选择Token时，没有授权提示，swap至灰。

### ISSUE THREAD

**Issue by lanetta55** [futuristic-swap/futuristic-swap.github.io#4]
![image](https://user-images.githubusercontent.com/104542636/200217502-1977704e-e332-4771-8871-abba3d87b99c.png)
![image](https://user-images.githubusercontent.com/104542636/200216973-44f1b8bf-6f4e-4a64-983b-7a11375111f9.png)

**Comment by jaaia** [comment]
done
